apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: claude-agent

resources:
  - namespace.yaml
  - rbac.yaml
  - network-policy.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: registry.digitalocean.com/globalcomix/claude-agent-server
    newTag: latest
  - name: registry.digitalocean.com/globalcomix/claude-agent-worker
    newTag: latest
